# Generated by Django 6.1.2 on 2026-10-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruitname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
