# Generated by Django 6.1.2 on 2026-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
