# Generated by Django 6.1.2 on 2026-10-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_employeemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='doj',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='experience',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='joining',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='login_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='dept',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='e_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
