# Generated by Django 6.1.2 on 2026-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employeemodel_description_employeemodel_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
