# Generated by Django 6.1.2 on 2026-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_employeemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
