# Generated by Django 6.1.2 on 2026-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_employeemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
