# Generated by Django 6.1.2 on 2026-10-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_employeemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='price',
        ),
    ]
