# Generated by Django 6.1.2 on 2026-10-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_student_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='name',
            new_name='std_name',
        ),
    ]
