# Generated by Django 6.1.2 on 2026-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_studentmodel_std_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
