# Generated by Django 6.1.2 on 2026-10-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name=10),
        ),
    ]
