# Generated by Django 6.1.2 on 2026-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_studentmodel_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(verbose_name=2)),
                ('gender', models.CharField()),
                ('sal', models.IntegerField()),
                ('address', models.CharField()),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
